== Repository View Context Resource API
A Collection of CRUD API endpoints used for interacting with CAP's Repository View Context Resource resource.

=== Create Resource

A `POST` request to the `/repository-view-context/{type}/{repositoryViewId}/resource?contexturi={contextUri}` endpoint, where `contextUri` will equal resource within the designated repository. This will result in thesaving the uploaded Resource.

==== Sample Request
include::../../../target/generated-snippets/create-resource/http-request.adoc[]

==== Sample Response
include::../../../target/generated-snippets/create-resource/http-response.adoc[]

==== Example Curl Request
include::../../../target/generated-snippets/create-resource/curl-request.adoc[]

=== Get Resources

A `GET` request to the `/repository-view-context/{type}/{repositoryViewId}/resource?contexturi={contextUri}` endpoint, where `contextUri` will equal resource within the designated repository. This will result in the rendering of the specified resource as a Repository View Context Resource.

==== Path Parameters
include::../../../target/generated-snippets/get-resources/path-parameters.adoc[]

==== Sample Request
include::../../../target/generated-snippets/get-resources/http-request.adoc[]

==== Sample Response
include::../../../target/generated-snippets/get-resources/http-response.adoc[]

==== Example Curl Request
include::../../../target/generated-snippets/get-resources/curl-request.adoc[]

=== Delete Resources

A `DELETE` request to the `/repository-view-context/{type}/{repositoryViewId}/resource?contexturi={contextUri}` endpoint, where `contextUri` will equal resource within the designated repository. This will result in the deletion of the specified resource as a Repository View Context Resource.

==== Path Parameters
include::../../../target/generated-snippets/delete-resources/path-parameters.adoc[]

==== Sample Request
include::../../../target/generated-snippets/delete-resources/http-request.adoc[]

==== Sample Response
include::../../../target/generated-snippets/delete-resources/http-response.adoc[]

==== Example Curl Request
include::../../../target/generated-snippets/delete-resources/curl-request.adoc[]

=== Check Fixity

A `GET` request to the `/repository-view-context/{type}/{repositoryViewId}/resource/fixity?contexturi={contextUri}` endpoint, where `contextUri` will equal resource within the designated repository. This will result in the execution of fixity for the specified resource as a Repository View Context Resource.

==== Path Parameters
include::../../../target/generated-snippets/check-fixity/path-parameters.adoc[]

==== Sample Request
include::../../../target/generated-snippets/check-fixity/http-request.adoc[]

==== Sample Response
include::../../../target/generated-snippets/check-fixity/http-response.adoc[]

==== Example Curl Request
include::../../../target/generated-snippets/check-fixity/curl-request.adoc[]
