== Repository View Metadata Children API
A Collection of CRUD API endpoints used for interacting with CAP's Repository View Context Metadata resource.

=== Create Metadata

A `POST` request to the `/repository-view-context/{type}/{repositoryViewId}/metadata?contexturi={contextUri}` endpoint, where `contextUri` will equal resource within the designated repository. This will result in the creation of the specified resource as a Repository View Context Metadata.

==== Sample Request
include::../../../target/generated-snippets/create-metadata/http-request.adoc[]

==== Sample Response
include::../../../target/generated-snippets/create-metadata/http-response.adoc[]

==== Example Curl Request
include::../../../target/generated-snippets/create-metadata/curl-request.adoc[]

=== Get Metadata

A `GET` request to the `/repository-view-context/{type}/{repositoryViewId}/metadata?contexturi={contextUri}` endpoint, where `contextUri` will equal resource within the designated repository. This will result in the rendering of the specified resource as a Repository View Context Metadata.

==== Sample Request
include::../../../target/generated-snippets/get-metadata/http-request.adoc[]

==== Sample Response
include::../../../target/generated-snippets/get-metadata/http-response.adoc[]

==== Example Curl Request
include::../../../target/generated-snippets/get-metadata/curl-request.adoc[]

=== Update Metadata

A `PUT` request to the `/repository-view-context/{type}/{repositoryViewId}/metadata?contexturi={contextUri}` endpoint, where `contextUri` will equal resource within the designated repository. This will result in updating the specified resource as a Repository View Context Metadata.

==== Sample Request
include::../../../target/generated-snippets/update-metadata/http-request.adoc[]

==== Sample Response
include::../../../target/generated-snippets/update-metadata/http-response.adoc[]

==== Example Curl Request
include::../../../target/generated-snippets/update-metadata/curl-request.adoc[]

=== Delete Metadata

A `DELETE` request to the `/repository-view-context/{type}/{repositoryViewId}/metadata?contexturi={contextUri}` endpoint, where `contextUri` will equal resource within the designated repository. This will result in the deletion of the specified resource as a Repository View Context Metadata.

==== Sample Request
include::../../../target/generated-snippets/delete-metadata/http-request.adoc[]

==== Sample Response
include::../../../target/generated-snippets/delete-metadata/http-response.adoc[]

==== Example Curl Request
include::../../../target/generated-snippets/delet-metadata/curl-request.adoc[]
