== Repository View Context Query API
A Collection of CRUD API endpoints used for interacting with CAP's Repository View Context Query resource.

=== Make Query

A `POST` request to the `/repository-view-context/{type}/{repositoryViewId}/query?contexturi={contextUri}` endpoint, where `contextUri` will equal resource within the designated repository. This will result in the execution of the provided query.

==== Sample Request
include::../../../target/generated-snippets/make-query/http-request.adoc[]

==== Sample Response
include::../../../target/generated-snippets/make-query/http-response.adoc[]

==== Example Curl Request
include::../../../target/generated-snippets/make-query/curl-request.adoc[]

=== Get Query Help

A `GET` request to the `/repository-view-context/{type}/{repositoryViewId}/query?contexturi={contextUri}` endpoint, where `contextUri` will equal resource within the designated repository. This will provide help on executing a query.

==== Sample Request
include::../../../target/generated-snippets/get-query-help/http-request.adoc[]

==== Sample Response
include::../../../target/generated-snippets/get-query-help/http-response.adoc[]

==== Example Curl Request
include::../../../target/generated-snippets/get-query-help/curl-request.adoc[]
