language: java

jdk:
  - oraclejdk8

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn clean test cobertura:cobertura jacoco:report coveralls:report

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: false
  target-branch: gh-pages
  github_token: "$GITHUB_TOKEN"
  local_dir: "./target/generated-docs"
  all_branches: true
  #on:
  #  branch: master
